---
title: "NVTA_Results"
author: "Sarah Lohmar"
date: "6/22/2021"
output:
  html_document:
    df_print: paged
    fig_caption: yes
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

ve.runtime <- ifelse(grepl('Flynn', normalizePath('~/')), 
                     file.path(dirname('~/'), 'Desktop/VE_4-1-0/'),
                       ifelse(grepl('Lohmar', normalizePath('~/')), 
                       file.path(dirname('~/'), '<PATH_TO_SARAH_VISIONEVAL>'),
                         ifelse(grepl('Englin', normalizePath('~/')), 
                         file.path(dirname('~/'), '<PATH_TO_ERIC_VISIONEVAL>'),
                          NA)))

knitr::opts_knit$set(root.dir = ve.runtime)

library(tidyverse)

```


```{r dvmt_plot}
readfile <- read.csv(file.path(ve.runtime, 'models', 'Scenario_Metrics_Marea.csv'))

#info for regional dvmt graphic 
dvmt <- readfile[ ,c(1,2,3,4,5,6,7,8)]
dvmt$regionalDVMT = rowSums(dvmt[,c(-1)])
dvmtbase = dvmt[1,9]
dvmt$modelName = substring(dvmt$modelName,8,15)
dvmt[1,1] = "NVTA_Base"
dvmt$regDVMTAbsDif = dvmt$regionalDVMT - dvmtbase
dvmt$regDVMTPerChange = (dvmt$regDVMTAbsDif/dvmtbase)*100
dvmt$color <- ifelse(dvmt$regDVMTPerChange > 0, "red","green")

dvmtplot1 <- data.frame(Model = dvmt$modelName,PercentChange = dvmt$regDVMTPerChange, 
                        color = dvmt$color)

ggplot(dvmtplot1, aes(x=Model, y=PercentChange, fill = color)) + 
  geom_bar(stat="identity") + theme_minimal() +
  labs(title = "Percent Change Regional DVMT", x = "Model Name", y = "Percent Change")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```